### ISSUE TITLE
GET/collections endpoint should work with hyphen in program_name field

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-API#47]
While using the endpoint GET/collections entering the collection LIDC-IDRI doesn't return any information. 

<img width="899" alt="lidc-idri collection" src="https://user-images.githubusercontent.com/16824894/114232555-0a0a2a00-994a-11eb-8c12-fd8c962df06d.PNG">

**Comment by bcli4d** [comment]
The /collections endpoint no longer takes a program_name parameter.
