### ISSUE TITLE
GET/attributes endpoint enhancement

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-API#48]
Add additional text that states end-user should enter full table ID to use the endpoint. 

<img width="899" alt="lidc-idri collection" src="https://user-images.githubusercontent.com/16824894/114233063-c6fc8680-994a-11eb-9f87-1afae822f23e.PNG">

**Comment by bcli4d** [comment]
The /collections endpoint no longer takes a program_name parameter.
