### ISSUE TITLE
GET/dicomMetadata endpoint returns error at top of the swagger document

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-API#49]
<img width="960" alt="dicommetaData timeout" src="https://user-images.githubusercontent.com/16824894/114233317-193da780-994b-11eb-8c84-b5faf677e2e0.PNG">

**Comment by bcli4d** [comment]
I added a section on timeouts to the [documentation](https://app.gitbook.com/@imagingdatacommons/s/api/#api-endpoints) .
